name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version: '1.24'
      - name: Build
        run: |
          cd backend
          go build ./...
      - name: Lint
        run: |
          cd backend
          go vet ./...
      - name: Test
        run: |
          cd backend
          go test -v ./...
